mysql:
  enable: true
  driver: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://localhost:3306/"
  database: "test"
  parameter: "useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"  #自动包含问号"?",无需填写
  username: "root"
  password: "123456"
#重载: /easy reload
